id = "kanayago"
name = "Kanayago"
description = "Kanayago LSP support for Ruby syntax checking"
version = "0.1.0"
schema_version = 1
authors = ["S.H."]
repository = "https://github.com/S-H-GAMELINKS/zed-kanayago"

[language_servers.kanayago]
name = "Kanayago"
languages = ["Ruby"]
