id = "kanayago"
name = "Kanayago"
description = "Ruby syntax checking using Kanayago LSP"
version = "0.1.0"
schema_version = 1
authors = ["S.H."]
repository = "https://github.com/S-H-GAMELINKS/zed-kanayago"
readme = "README.md"
license = "MIT"

[language_servers.kanayago]
name = "Kanayago LSP"
languages = ["Ruby"]
